### ISSUE TITLE
Play/Pause Button

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#105]
<img width="154" alt="Screen Shot 2021-05-05 at 3 33 38 PM" src="https://user-images.githubusercontent.com/22364036/117218039-4862ff80-adb7-11eb-9191-71b02db01c58.png">

<img width="197" alt="Screen Shot 2021-05-05 at 3 34 37 PM" src="https://user-images.githubusercontent.com/22364036/117218112-6892be80-adb7-11eb-8f13-ec0ae8f08a85.png">

Is the Pause icon from heroicons.com? The corners of the vertical lines are looking a bit too round in comparison to the Play button's sharper corners. If it is I'll grab it, make the tweaks, and tag you in Figma.

**Comment by kylewelsby** [comment]
the rounded corners fit with the aesthetics of the rounded corners on artwork around the site, so I don't feel a change is needed here.
