### ISSUE TITLE
Mobile - Menu

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#106]
<img width="268" alt="Screen Shot 2021-05-06 at 12 39 08 PM" src="https://user-images.githubusercontent.com/22364036/117355966-11005b80-ae68-11eb-8c03-2108e99d32c8.png">

<img width="375" alt="Menu" src="https://user-images.githubusercontent.com/22364036/117356624-d0551200-ae68-11eb-999c-08e58728bd71.png">

Is it possible to still respect the nav bar when selecting the menu button in case people would still want to search from here?

Let's make sure that these Conthrax titles are uppercase as well to keep it consistent with the rest of the site.

Also, there's no visual cue to let people know that they can close the menu or go back. Can we add this button to the bottom?

**Comment by kylewelsby** [comment]
fixed in 407167cc43a06da873519ea42267541d297973b7

**Comment by dorianromero** [comment]
![IMG_8498](https://user-images.githubusercontent.com/22364036/118780296-bf30db80-b840-11eb-9b49-cfc33225f6bb.PNG)

Not seeing any changes to this still. Can we reopen this issue?
