### ISSUE TITLE
(P1) Track & Tracklist Page - Artist Name + Date/Location Using Old Text Style

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#154]
V4 Track page
<img width="547" alt="Screen Shot 2021-05-19 at 6 14 34 PM" src="https://user-images.githubusercontent.com/22364036/118906706-239c7b00-b8d3-11eb-80b7-3555f1f92cdb.png">

V4 Tracklist page
![Screen Shot 2021-05-20 at 12 08 59 PM](https://user-images.githubusercontent.com/22364036/119035208-2b583000-b964-11eb-91a5-8b1ffda266a4.png)

I believe these are the last instances where the old serif text style is still in play. Let's update this to SystemUI and make it full opacity as well.

**Comment by kylewelsby** [comment]
fixed
