### ISSUE TITLE
Is there a way to get links to all the soulection shows?

### ISSUE THREAD

**Issue by dkvdm** [kylewelsby/v4.soulectiontracklists.com#246]
Hi there!
First of all, love your work! I used to keep a personal mirror of all my soulection shows locally for Roon, and I would like to restart this.
Is there a way that I can get links to all the soulection shows on soundcloud? I should be able to take over from there.

Many thanks,
Dennis

**Comment by kylewelsby** [comment]
Hey @dkvdm 

Sorry for the late reply,  

Yes there is a way to get all Soulection shows directly from the database via [supabase.js](https://supabase.com/docs/reference/javascript/select)

```javascript
import { createClient } from '@supabase/supabase-js'
const supabase = createClient('https://zcrfswljwarptffbdqtr.supabase.co', '{EmailMeForKey<kyle@mekyle.com>}')

const { data, error } = await supabase
  .from('shows')
  .select("links")
  .eq('profile', 'QiEFFErt688')
  .eq('state', 'published')
  .overlaps('tags', [15])
  .order('published_at', { ascending: false })
  .limit(20)
console.log(data)
```
