### ISSUE TITLE
Image Border Radius

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#68]
<img width="524" alt="Screen Shot 2021-04-12 at 2 56 02 PM" src="https://user-images.githubusercontent.com/22364036/114467894-76319b80-9b9f-11eb-8ffa-60067dc1412f.png">

<img width="498" alt="Screen Shot 2021-04-12 at 3 06 27 PM" src="https://user-images.githubusercontent.com/22364036/114468637-aaf22280-9ba0-11eb-93db-0c63e66d7c27.png">

Artwork is looking a bit too round, let's give all artwork a border radius of 2.5px instead.

**Comment by kylewelsby** [comment]
I kinda like it, but on mobile and its a bit over the top, so I dropped it down to `rounded-xl` for mobile and kept `rounded-2xl` for desktop

https://tailwindcss.com/docs/border-radius#rounded-corners
