### ISSUE TITLE
Home Page - Max Image Size

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#71]
<img width="834" alt="Screen Shot 2021-04-12 at 11 03 06 PM" src="https://user-images.githubusercontent.com/22364036/114509784-c97d0b80-9bea-11eb-8f5e-2fd97b390cb5.png">

These images look a bit big on desktop, seeing it as 512px when I inspect. Let's scale these down to around 300-350px.

**Comment by kylewelsby** [comment]
fixed in 93e7253 image size is now 360px
