### ISSUE TITLE
Footer - Max Width

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#72]
<img width="1279" alt="Screen Shot 2021-04-13 at 12 20 05 AM" src="https://user-images.githubusercontent.com/22364036/114512543-144c5280-9bee-11eb-8a41-63c997f4e5f0.png">

Footer structure looks good, but let's give the container a smaller width/more padding and make it a full black (#000000) background to give it contrast from the overall page background.

**Comment by kylewelsby** [comment]
this is fixed 4ab180a50bdabec1519e76577af58d1602769d72

**Comment by dorianromero** [comment]
Hmm it's still coming through like this on v4.

<img width="1277" alt="Screen Shot 2021-05-03 at 2 04 57 PM" src="https://user-images.githubusercontent.com/22364036/116933557-8d9cfb00-ac18-11eb-847f-8bc26b1621de.png">
