### ISSUE TITLE
Show 500 - Shows Gallery

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#80]
<img width="1278" alt="Screen Shot 2021-04-14 at 12 08 56 PM" src="https://user-images.githubusercontent.com/22364036/114786854-af9b1000-9d33-11eb-943d-cc180b8c6b8b.png">

<img width="475" alt="Screen Shot 2021-04-14 at 3 20 19 PM" src="https://user-images.githubusercontent.com/22364036/114787604-f0475900-9d34-11eb-8f64-035bac276b5b.png">

I like the concept of this section, but it feels very overwhelming and a lot to scroll through without an easy way to get back to the top/navigate through the page.

Would we be able to divide the sections by year? And give them an 8px margin so they can breathe a bit? Reference attached.

**Comment by kylewelsby** [comment]
closed by 93e7253<img width="2537" alt="Screenshot 2021-04-29 at 00 34 44" src="https://user-images.githubusercontent.com/110469/116485307-cfc5e580-a882-11eb-9962-485879e2b93a.png">

Year markers added, and space around artwork is given, reopen issue if you think so


<img width="2537" alt="Screenshot 2021-04-29 at 00 34 44" src="https://user-images.githubusercontent.com/110469/116485307-cfc5e580-a882-11eb-9962-485879e2b93a.png">Not sure if to have constrained width (for large screens) or have the full width as current.

**Comment by dorianromero** [comment]
Nice!

We can go full width on these divs, but yeah I think we can account for a bit more left and right margin (16px to 40px) and top margin from the header (32px to 80px)) to break up the sections of years like below.

<img width="1275" alt="Screen Shot 2021-05-03 at 1 58 52 PM" src="https://user-images.githubusercontent.com/22364036/116932897-b40e6680-ac17-11eb-821e-37f0a48ded31.png">
