### ISSUE TITLE
500 Page - Div

### ISSUE THREAD

**Issue by dorianromero** [kylewelsby/v4.soulectiontracklists.com#83]
<img width="1266" alt="Screen Shot 2021-04-14 at 4 28 50 PM" src="https://user-images.githubusercontent.com/22364036/114793106-82079400-9d3e-11eb-9212-4c2cfad829a1.png">

<img width="1232" alt="Screen Shot 2021-04-14 at 4 38 26 PM" src="https://user-images.githubusercontent.com/22364036/114793713-d8c19d80-9d3f-11eb-83b1-3a987728a42d.png">

<img width="1137" alt="Screen Shot 2021-04-14 at 4 49 42 PM" src="https://user-images.githubusercontent.com/22364036/114794501-76699c80-9d41-11eb-9629-319d590cbc12.png">

Card:
- lets give the image and text a margin of 64px so there's good room to breathe for the text
- Update alignment to align-itmes: flex-end, and give a 40px bottom margin to the text+button component

Zane Lowe Interview:
- missing the title

Container Margin:
- change to 200px instead of 40px to give focus to each piece of content as users scroll down the page

**Comment by kylewelsby** [comment]
most fixed in 93e7253

Currently missing:
- [x] Zane Lowe Interview
